White/Components/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using White.Data;

namespace HidroProduct.Components
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private readonly AppDbContext context;

        public CategoryMenuViewComponent(
            AppDbContext context
            )
        {
            this.context = context;
        }

        public IViewComponentResult Invoke()
        {
            var model = context.Categories.ToList();
            return View(model);
        }
    }
}

White/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HidroProduct</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HidroProduct.styles.css" asp-append-version="true" />
</head>
<body style="background-color:#eff5f5">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HidroProduct</a>
                <a class="navbar-brand"  href="#">Hakkında</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @await Component.InvokeAsync("CategoryMenu")
                    </ul>
                    <form asp-controller="Home" asp-action="Search" method="get" class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="ara..." name="keyword" aria-label="Search" value="@ViewContext.HttpContext.Request.Query["keyword"].ToString()">
                        <button class="btn btn-success" type="submit">
                            <i class="bi bi-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - HidroProduct - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

White/Views/Shared/_ProductListPartial.cshtml
 @using White.Data;
@using White;

@model IEnumerable<Product>
  

     <div class="row row-cols-1 row-cols-md-5 g-4">
    @foreach (var product in Model)
    {
        <div class="col ">
            <div class="card h-100 box ">
                <a asp-action="Product" asp-route-id="@product.id">
                    <img class="card-img-top" src="@product.Image" />
                </a>
                <div class="card-body shadow">
                    <div class="card-title h6 text-truncate">
                        <a asp-action="Product" asp-route-id="@product.id" class="text-decoration-none">
                            @product.Name
                        </a>
                    </div>
                    <div class="card-text">@product.Price.ToString("c2")</div>
                    <div class="small">@product.Category!.Name</div>
                    <div class="card-text">@product.SupplierName</div>

                    <div class="">
                        <a class="btn btn-outline-primary" asp-route="Product" asp-route-id="@product.id" asp-route-name="@product.Name.ToSafeUrlString()">
                            <i class="fa fa-search"></i> İncele
                        </a>
                </div> 
                </div>
            </div>
        </div>
    }
</div>